services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=YourStrongPassword123!"
      - "MSSQL_PID=Express"
    ports:
      - "1453:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata:
